// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShyp5QLp9TQBFijWHM4dYWV0Fh-P5eag',
    appId: '1:799326031228:web:b41ff91a72a673f3f068f9',
    messagingSenderId: '799326031228',
    projectId: 'flutter-real-time-d860b',
    authDomain: 'flutter-real-time-d860b.firebaseapp.com',
    databaseURL: 'https://flutter-real-time-d860b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-real-time-d860b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_XpH0HVbFDiGpTov7FFEVjs_lhmmpqg',
    appId: '1:799326031228:android:583025b39ff7833ef068f9',
    messagingSenderId: '799326031228',
    projectId: 'flutter-real-time-d860b',
    databaseURL: 'https://flutter-real-time-d860b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-real-time-d860b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgS1f09baS2zJgjYzrJrfA5_Ma-67qhdE',
    appId: '1:799326031228:ios:c38277b2986843e6f068f9',
    messagingSenderId: '799326031228',
    projectId: 'flutter-real-time-d860b',
    databaseURL: 'https://flutter-real-time-d860b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-real-time-d860b.appspot.com',
    iosBundleId: 'com.example.roomRentStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgS1f09baS2zJgjYzrJrfA5_Ma-67qhdE',
    appId: '1:799326031228:ios:ac586b7e7d40290df068f9',
    messagingSenderId: '799326031228',
    projectId: 'flutter-real-time-d860b',
    databaseURL: 'https://flutter-real-time-d860b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-real-time-d860b.appspot.com',
    iosBundleId: 'com.example.roomRentStudent.RunnerTests',
  );
}
